version: '3.8'

services:
  icd-10-api:
    image: node:18.12.1-alpine
    user: ${USERID}
    working_dir: /var/workspace
    environment:
      # default npm cache location (~/.npm) is not writeable in the container
      npm_config_cache: /var/workspace/.npm_cache
    volumes:
      - ${DEV_OVERLAY_DIR}:/var/workspace/:cached
    ports:
      - "3000:3000" # nodejs express server application port to access it directly
      - "9229:9229" # nodejs debugger port
    # environment:
    #   MAX_SEARCH_WORDS: "6"
    command:
      - sleep
      - infinity
