name: Build Docker Image For Branch

on:
  workflow_dispatch:
    inputs:
      architecture:
        type: choice
        required: true
        default: amd64
        options:
          - amd64
          - arm64
          - both
      imageTag:
        type: string
        required: true
        description: "For example: 1.0.0"

jobs:
  build-docker-image:
    name: Build Docker Image for ${{ inputs.imageTag }}
    uses: dot-base/.github/.github/workflows/build-docker-image-manually.yml@main
    with:
      architecture: ${{ inputs.architecture }}
      imageTag: ${{ inputs.imageTag }}
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      CR_PAT: ${{ secrets.CR_PAT }}
