name: Create Pre-Release

on:
    pull_request:
        branches:
            - main
        types: [closed]

jobs:
  create-pre-release:
    name: Create Pre-Release
    uses: dot-base/.github/.github/workflows/create-pre-release.yml@main
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
