name: 🆕 Create Release

on: 
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The branch with the changes that shall be released.
        default: "main"

jobs:
  create-release:
    name: Create Release
    uses: dot-base/.github/.github/workflows/create-release.yml@feat/tag-based-release
    with:
      branch: ${{ inputs.branch }}
      SERVICE_TYPE: node
    secrets:
      GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
      CR_PAT: ${{ secrets.CR_PAT }}
