name: 🚒 Create Hotfix Release PR

on:
    workflow_dispatch:
        inputs:
            branch:
                type: string
                description: The hotfix branch with the fix that shall be released.
                required: true
                default: fix/

jobs:
    create-release-PR:
        name: Create a PR from the hotfix branch into 'release'
        uses: dot-base/.github/.github/workflows/create-release-pr.yml@main
        with:
            branch: ${{ inputs.branch }}
        secrets:
            GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
            GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
