name: Sync PR After Merge

on:
  pull_request:
    branches:
      - 'sync/*'
    types:
      - closed

jobs:
  sync-pr-after-merge:
    name: Create Release
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'sync(hotfix)')
    uses: dot-base/.github/.github/workflows/sync-pr-after-merge.yml@main
    secrets:
      GH_BOT_PAT: ${{ secrets.GH_BOT_PAT }}
    with:
      SYNC_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
